/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/c3vA7jMZytT
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function Home() {
  return (
    (<div className="flex flex-col min-h-screen bg-white dark:bg-gray-800">
      <header className="flex items-center justify-between px-8 py-4 border-b">
        <Link className="flex items-center space-x-2" href="#">
          <IconMedical className="h-8 w-8 text-blue-500" />
          <span className="text-2xl font-semibold text-gray-900 dark:text-white">Clinic</span>
        </Link>
        <nav className="hidden md:flex space-x-10">
          <Link
            className="text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400"
            href="#">
            About
          </Link>
          <Link
            className="text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400"
            href="#">
            Services
          </Link>
          <Link
            className="text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400"
            href="#">
            Team
          </Link>
          <Link
            className="text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400"
            href="#">
            Contact
          </Link>
        </nav>
        <div className="flex items-center space-x-4 md:space-x-2">
          <Button className="md:hidden" variant="outline">
            Menu
          </Button>
          <Button className="hidden md:inline-flex" variant="outline">
            Sign in
          </Button>
          <Button className="hidden md:inline-flex">Sign Up</Button>
        </div>
      </header>
      <main className="flex-grow">
        <section className="text-center py-20 px-8 bg-blue-500 text-white">
          <h1 className="text-4xl font-semibold">Welcome to Clinic Management</h1>
          <p className="mt-4 text-xl">We provide the best healthcare services</p>
          <div className="mt-8">
            <Button>Learn More</Button>
          </div>
        </section>
        <section className="py-20 px-8" id="about">
          <h2 className="text-4xl font-semibold text-center">About Us</h2>
          <p
            className="mt-4 max-w-2xl mx-auto text-center text-gray-600 dark:text-gray-400">
            We are a team of dedicated healthcare professionals providing top quality healthcare services.
          </p>
        </section>
        <section className="py-20 px-8 bg-gray-100 dark:bg-gray-900" id="services">
          <h2 className="text-4xl font-semibold text-center">Our Services</h2>
          <div className="mt-8 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <Card>
              <div />
              <div>
                <div>Service 1</div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
              </div>
            </Card>
            <Card>
              <div />
              <div>
                <div>Service 2</div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
              </div>
            </Card>
            <Card>
              <div />
              <div>
                <div>Service 3</div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
              </div>
            </Card>
          </div>
        </section>
        <section className="py-20 px-8" id="team">
          <h2 className="text-4xl font-semibold text-center">Our Team</h2>
          <div className="mt-8 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <Card>
              <Avatar alt="Team Member 1" src="/placeholder.svg?height=200&width=200" />
              <div>
                <div>Team Member 1</div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
              </div>
            </Card>
            <Card>
              <Avatar alt="Team Member 2" src="/placeholder.svg?height=200&width=200" />
              <div>
                <div>Team Member 2</div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
              </div>
            </Card>
            <Card>
              <Avatar alt="Team Member 3" src="/placeholder.svg?height=200&width=200" />
              <div>
                <div>Team Member 3</div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
              </div>
            </Card>
          </div>
        </section>
        <section className="py-20 px-8 bg-blue-500 text-white" id="contact">
          <h2 className="text-4xl font-semibold text-center">Contact Us</h2>
          <div className="mt-8 max-w-md mx-auto">
            <form className="grid gap-4">
              <Input className="rounded-md" placeholder="Your Name" type="text" />
              <Input className="rounded-md" placeholder="Your Email" type="email" />
              <textarea className="rounded-md" placeholder="Your Message" rows="4" />
              <Button type="submit">Send Message</Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="py-4 px-8 text-center border-t">
        <p className="text-sm text-gray-600 dark:text-gray-400">© Clinic Management. All Rights Reserved.</p>
      </footer>
    </div>)
  );
}


function IconMedical(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round">
      <path
        d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15" />
      <path d="M11 12 5.12 2.2" />
      <path d="m13 12 5.88-9.8" />
      <path d="M8 7h8" />
      <circle cx="12" cy="17" r="5" />
      <path d="M12 18v-2h-.5" />
    </svg>)
  );
}
